### ISSUE TITLE
Refactor LidarDriver & pls_to_geotiff

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#237]
LidarDriver, from an object oriented perspective, is problematic. It has come up several times in the past, but with the inclusion of features from #171 (the csv file driver), the problem has become glaring and needs to be fixed.

Something that really pairs well with this is removing some code from pls_to_geotiff, which shouldn't be directly in main.

**Things that will need to be done**
- [ ] A code review, which will identify:
- [ ] Functions that can be broken into smaller functions, and
- [ ] Better locations for said functions, that pairs them with the objects they affect.
