### ISSUE TITLE
Add Driver Classes to UML diagrams

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#286]
- [x] Class diagram has driver classes
- [x] Relationship diagram has driver classes
- [x] Driver classes are denoted by a change in bg color
