### ISSUE TITLE
Research techniques & principles for cleaner, faster & more testable software design

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#305]
At first I was going to try writing more unit tests for the existing code, but I started thinking about testability, and how I could rearrange a few things to make them more testable. Then I realized if I was going to do that, then the best way to make unit tests would be to just start working on reorganizing the code, since I can bake testability into it at that point.

Problems I need to find answers to:
- [x] Dependencies make testing difficult from time to time
- [x] Bloated (long & complex) functions make testing overly complex from time to time
- [x] Fitting process is hard to augment without either slowing the code down or producing duplicate code with only slight changes made from the original
- [x] Software needs to be as cheap to convert to a multi-threaded program as possible.

Limitations I've found to possible solutions include:
- Virtual functions aren't determined at compiled-time, so they cause additional overhead when called. This cannot be allowed to influence the fitting or other portions that are repeated frequently during run-time.
- Something similar can happen when using abstract classes / interfaces.
- Breaking up functions into smaller functions in general may introduce additional overhead, although prior research convinced me this is negligible as long as I keep in mind what can make code more cacheable and inline-able.

I'll need to research these and figure out how/when they are bad.

**Acceptance criteria**
- [x] Research designing for testability
- [x] Research test coverage strategies/'how to unit test'
- [x] Research virtual functions & abstract classes, and the options we have for control flow that minimizes overhead
- [x] Research what makes a compiler able to reduce overhead of function calls with automated in-lining, caching and other things.
- [x] Typical designs for multi-threaded programs.

I may add more as I go and feel the need.

**Comment by SpencerFleming** [comment]
In my research I learned a few tricks I can employ to squeeze some additional performance out of our software once it is reorganized. I feel like I have a better understanding of some of the suggestions I received from Cathie over the course of my time on this project as well.

In the tasks for this epic I make several suggestions as to what I could do to apply my research to the project. I'm not the only person working on this project and none of those suggestions are set in stone, naturally, but I figured documenting the ideas would be smart since I can hardly remember what I ate for breakfast today.

There is one last thing that I wanted to gain some more background information on for our revision: Multi-thread-friendly software design. We need to make sure our revision won't be hard to change into a multi-threaded program when it becomes time.

**Comment by SpencerFleming** [comment]
Solutions found for problems thus far:
- For dependencies causing difficulty with unit testing, we can create interfaces that allow us to replace dependencies with mock variants of those dependencies. In performance critical sections, we can still do this without the abstraction of an interface, but it will just be a little more effort to maintain. It's worth it for the performance boost though.

- Bloated and complex functions are absolutely not necessary *except* in performance critical sections. Within performance critical sections we will likely want to reduce the number of functions as much as possible. That said, control flow statements that may be needed in a large function may be just as expensive as the function calls in some cases, so it's really a case by case issue.

- The issue of making fitting configurable is heavily related to the issue mentioned above. If I can convert pieces of the fitting process into inline functions and get the compiler to cooperate with me, then I might be able to avoid duplicate code AND avoid unnecessary control flow statements. There could be a diagnostic fitter function and a non-diagnostic fitter function, but all they would do is call a slightly different sequence of functions. I'll still have to look at the code more to see if this is a plausible solution though.

**Comment by SpencerFleming** [comment]
Multi-threading stuff was easier than I thought, partially because I learned that it is still too early to be asking those questions to some extent. I'll ask Cathie about it though to make sure.
